### ISSUE TITLE
Cannot find module '@abandonware/bluetooth-hci-socket'

### ISSUE THREAD

**Issue by Sergio-tix** [AlCalzone/ioBroker.ble#38]
Hi Alcalzone,
i got this error after updating ble to 0.6.0.
`
ble.0 | 2019-01-12 01:51:14.813 | error | unhandled promise rejection: Error: Cannot find module '@abandonware/bluetooth-hci-socket'
-- | -- | -- | --
`
I returned to version 0.5.2, but the error is the same.
I will update the node.js 8 to 10.15, the result has not changed.
I tried:
`npm install @abandonware/bluetooth-hci-socket`
_____________________
![default](https://user-images.githubusercontent.com/18720428/51063898-163d9a80-160e-11e9-8b9d-a9433607e22f.PNG)

**Comment by AlCalzone** [comment]
You have to execute the install command in the adapter directory, that is `/opt/iobroker/node_modules/iobroker.ble`

**Comment by Sergio-tix** [comment]
Here is my decision:
`
iobroker del ble
`
and
`iobroker add ble`
