### ISSUE TITLE
Cannot find module '../build/Release/binding.node'

### ISSUE THREAD

**Issue by zuvielx9** [AlCalzone/ioBroker.ble#19]
Hi Alcalzone,

i got this error after updating to 4.0.2.

![image](https://user-images.githubusercontent.com/34238665/37961731-5c339f1a-31b9-11e8-84ba-9df45b1ea96f.png)

can you help?

**Comment by AlCalzone** [comment]
Thats most likely coming from the `noble` packet. If there's a folder `/opt/iobroker/node_modules/iobroker.ble/node_modules/noble`, open it and execute `npm install --production` there.

**Comment by zuvielx9** [comment]
it works, thank you!
